from hugag.materials.rhythm import (
    rhythm_handler_one,
    rhythm_handler_two,
    silence_handler,
)

rhythm_material_list = [
    silence_handler,  # voice 1
    silence_handler,
    silence_handler,
    silence_handler,
    silence_handler,
    silence_handler,
    silence_handler,
    rhythm_handler_one,
    rhythm_handler_one,
    rhythm_handler_one,
    silence_handler,  # voice 2
    silence_handler,
    silence_handler,
    silence_handler,
    silence_handler,
    silence_handler,
    silence_handler,
    silence_handler,
    silence_handler,
    silence_handler,
    rhythm_handler_one,  # voice 3
    rhythm_handler_one,
    silence_handler,
    silence_handler,
    silence_handler,
    silence_handler,
    silence_handler,
    silence_handler,
    silence_handler,
    silence_handler,
    rhythm_handler_two,  # voice 4
    rhythm_handler_two,
    rhythm_handler_two,
    rhythm_handler_two,
    rhythm_handler_two,
    rhythm_handler_two,
    rhythm_handler_two,
    rhythm_handler_two,
    rhythm_handler_two,
    rhythm_handler_two,
    silence_handler,  # voice 5
    silence_handler,
    rhythm_handler_one,
    rhythm_handler_one,
    silence_handler,
    silence_handler,
    silence_handler,
    rhythm_handler_one,
    rhythm_handler_one,
    rhythm_handler_one,
]
